Jenkins: set UNITY_VERSION and check Unity Editor existence

diff --git a/Jenkins/Dockerfile b/Jenkins/Dockerfile
--- a/Jenkins/Dockerfile
+++ b/Jenkins/Dockerfile
@@ -23,7 +23,11 @@ ENV NVIDIA_DRIVER_CAPABILITIES graphics,display,utility
 ADD "https://gitlab.com/nvidia/container-images/vulkan/raw/master/nvidia_icd.json" /etc/vulkan/icd.d/nvidia_icd.json
 RUN chmod 644 /etc/vulkan/icd.d/nvidia_icd.json
 
-RUN curl -fLo UnitySetup https://beta.unity3d.com/download/76626098c1c4/UnitySetup-2020.3.3f1 \
+ENV UNITY_VERSION="2020.3.3f1"
+
+RUN curl -fLo UnitySetup https://beta.unity3d.com/download/76626098c1c4/UnitySetup-${UNITY_VERSION} \
     && chmod +x UnitySetup \
     && yes | ./UnitySetup --unattended --install-location=/opt/Unity --components=Unity,Windows-Mono,Mac-Mono \
-    && rm UnitySetup
+    && rm UnitySetup \
+    && [ -x /opt/Unity/Editor/Unity ] || echo "ERROR: /opt/Unity/Editor/Unity doesn't exist" \
+    && [ -x /opt/Unity/Editor/Unity ] || exit 1
