Jenkinsfile: Add bundleScenariosRunner step which creates another .zip with runner included
* it creates *-linux64-${GIT_BRANCH}-${JENKINS_BUILD_ID}-runner.zip
  with the simulator from *-linux64-${GIT_BRANCH}-${JENKINS_BUILD_ID}.zip
  and the runner pulled from docker image specified in
  SCENARIOS_RUNNER_DOCKER_TAG (hdrp/scenarios/runner/jenkins:latest by default).

[AUTO-4929] Modify the Jenkins job that builds Simulator to install the scenario runner files

Signed-off-by: Martin Jansa <martin.jansa@lge.com>

diff --git a/Jenkins/Jenkinsfile b/Jenkins/Jenkinsfile
--- a/Jenkins/Jenkinsfile
+++ b/Jenkins/Jenkinsfile
@@ -27,7 +27,9 @@ pipeline {
     booleanParam(name: "FORCE_CHECK", defaultValue: false, description: "")
     booleanParam(name: "FORCE_TEST", defaultValue: false, description: "")
     booleanParam(name: "UPLOAD_TO_ECR", defaultValue: false, description: "Enable uploading docker image with build simulator zip to the ECR.")
+    booleanParam(name: "BUNDLE_SCENARIOS_RUNNER", defaultValue: false, description: "Enable creating another zip archive with linux simulator bundled with scenarios runner.")
     string(name: "CLOUD_URL", defaultValue: "${SIMULATOR_WISE_STAGING_URL}", description: "")
+    string(name: "SCENARIOS_RUNNER_DOCKER_TAG", defaultValue: "hdrp/scenarios/runner/jenkins:latest", description: "Repo and tag of scenarios runner docker image which will be bundled in zip archive")
     string(name: 'WISE_AWS_ECR_ACCOUNT_ID', defaultValue: '853285614468', description: 'The AWS account ID whose ECR will be used', trim: true)
     string(name: 'WISE_AWS_ECR_REGION', defaultValue: 'us-east-1', description: 'The AWS region where the ECR is located', trim: true)
     credentials( name: 'WISE_AWS_ECR_CREDENTIALS_ID', required: true, defaultValue: "simulator--aws-credentials", description: 'The credentials to be used for accessing the ECR', credentialType: 'com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl')
@@ -314,6 +316,61 @@ pipeline {
       }
 
     } // macOS
+
+    stage("bundleScenariosRunner") {
+      when {
+        anyOf {
+            buildingTag()
+            branch 'master'
+            environment name: "BUNDLE_SCENARIOS_RUNNER", value: "true"
+        }
+      }
+
+      steps {
+        dir("Jenkins") {
+          sh """
+            if ! docker pull ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG; then
+              echo "ABORT: cannot pull ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG"
+              exit 1
+            fi
+            TEMP_CONT=`docker create ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG --name scenarios-runner-tmp`
+            if ! docker cp \$TEMP_CONT:/usr/share/scenarios-runner/scripts .; then
+              echo "ABORT: ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} doesn't have /usr/share/scenarios-runner/scripts directory"
+              docker rm \$TEMP_CONT
+              exit 1
+            fi
+            if ! docker cp \$TEMP_CONT:/etc/wise-image-info.source .; then
+              echo "ABORT: ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} doesn't have /etc/wise-image-info.source file"
+              docker rm \$TEMP_CONT
+              exit 1
+            fi
+            docker rm \$TEMP_CONT
+
+            rm -rf dist
+            mkdir -p dist/docker
+            docker save ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} > dist/docker/lgsvl-simulator-scenarios-runner.tar
+            cp scripts/install-testcase-runtime.sh scripts/scenario_runner.sh dist
+
+            ZIP=../*-linux64-${GIT_BRANCH}-${JENKINS_BUILD_ID}.zip
+
+            unzip -o \$ZIP
+            UNZIP=`basename \$ZIP | sed 's/\\.zip\$//g'`
+            echo "INFO: bundling simulator from \$UNZIP with scenarios runner from docker image \$SCENARIOS_RUNNER_DOCKER_TAG:"
+            cat wise-image-info.source
+
+            dist/install-testcase-runtime.sh \$UNZIP copy
+            zip --symlinks -r ../\$UNZIP-runner.zip \$UNZIP
+            rm -rf dist
+            rm -f wise-image-info.source
+          """
+        }
+      }
+      post {
+        success {
+          archiveArtifacts "*-linux64-${GIT_BRANCH}-${JENKINS_BUILD_ID}-runner.zip"
+        }
+      }
+    }
 
     stage("uploadECR") {
       when {
