Jenkinsfile-Release: upload docker image with built simulator zip to ECR
AUTO-3805 WISE - Deployment: Arrange for Jenkins build to create a Simulator container and upload to ECR

Signed-off-by: Martin Jansa <martin.jansa@lge.com>

diff --git a/Jenkins/Jenkinsfile-Release b/Jenkins/Jenkinsfile-Release
--- a/Jenkins/Jenkinsfile-Release
+++ b/Jenkins/Jenkinsfile-Release
@@ -16,7 +16,11 @@ pipeline {
   }
 
   parameters {
-    string(name: "CLOUD_URL", defaultValue: "${SIMULATOR_WISE_BETA_URL}", description: "")
+    booleanParam(name: "UPLOAD_TO_ECR", defaultValue: false, description: "Enable uploading docker image with build simulator zip to the ECR.")
+    string(name: "CLOUD_URL", defaultValue: "${SIMULATOR_WISE_STAGING_URL}", description: "")
+    string(name: 'WISE_AWS_ECR_ACCOUNT_ID', defaultValue: '853285614468', description: 'The AWS account ID whose ECR will be used', trim: true)
+    string(name: 'WISE_AWS_ECR_REGION', defaultValue: 'us-east-1', description: 'The AWS region where the ECR is located', trim: true)
+    credentials( name: 'WISE_AWS_ECR_CREDENTIALS_ID', required: true, defaultValue: "simulator--aws-credentials", description: 'The credentials to be used for accessing the ECR', credentialType: 'com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl')
   }
 
   environment {
@@ -270,6 +274,54 @@ pipeline {
 
     } // Linux
 
+    stage("uploadECR") {
+      when {
+        anyOf {
+            buildingTag()
+            branch 'master'
+            environment name: "UPLOAD_TO_ECR", value: "true"
+        }
+      }
+
+      steps {
+        dir("Jenkins") {
+          sh "echo Using credentials ${WISE_AWS_ECR_CREDENTIALS_ID}"
+          withCredentials([[credentialsId: "${WISE_AWS_ECR_CREDENTIALS_ID}", accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY', $class: 'AmazonWebServicesCredentialsBinding']]) {
+            sh """
+              DOCKER_REGISTRY="${WISE_AWS_ECR_ACCOUNT_ID}.dkr.ecr.${WISE_AWS_ECR_REGION}.amazonaws.com"
+              DOCKER_REPO="wise/simulator"
+              GIT_TAG_FOR_ECR=`echo ${GIT_TAG} | tr / -  | tr [:upper:] [:lower:]`
+              DOCKER_TAG="version__\$GIT_TAG_FOR_ECR"
+
+              docker-compose pull aws-cli
+              if ! UID=`id -u` docker-compose run --rm aws-cli ecr get-login-password --region $WISE_AWS_ECR_REGION | docker login --username AWS --password-stdin \$DOCKER_REGISTRY; then
+                echo "ABORT: bad AWS credentials?"
+                exit 1
+              fi
+              if ! UID=`id -u` docker-compose run --rm aws-cli ecr create-repository --repository-name \$DOCKER_REPO --region $WISE_AWS_ECR_REGION; then
+                echo "INFO: aws-cli ecr create-repository --repository-name \$DOCKER_REPO --region $WISE_AWS_ECR_REGION failed - assuming that it's because the repo already exists in ECR"
+              fi
+
+              cd ../Docker
+              cp -al ../*-linux64-${GIT_TAG}.zip .
+              docker build --pull --no-cache \
+                  --build-arg "simulator_zipfile=*-linux64-${GIT_TAG}.zip" \
+                  --build-arg image_git_describe=\$(git describe --always --tags) \
+                  --build-arg image_uuidgen=\$(uuidgen) \
+                  -t \$DOCKER_REGISTRY/\$DOCKER_REPO:\$DOCKER_TAG .
+              docker push \$DOCKER_REGISTRY/\$DOCKER_REPO:\$DOCKER_TAG
+              rm -fv *-linux64-${GIT_TAG}.zip
+
+              docker image rm \
+                \$DOCKER_REGISTRY/\$DOCKER_REPO:\$DOCKER_TAG
+              docker container prune -f
+              docker volume prune -f
+              docker image prune -f
+            """
+          }
+        }
+      }
+    } // uploadECR
   } // stages
 
   post {
