[Build] Jenkins: Show better error message when SCENARIOS_RUNNER_DOCKER_TAG is missing or empty
* https://auto-jenkins.lgsvl.net/job/simulator-release-cloud/30 failed with:

  [Pipeline] { (bundleScenariosRunner)
  [Pipeline] dir
  03:57:22  Running in /home/jenkins/workspace/simulator-cloud-release-2019.3.15f1/Jenkins
  [Pipeline] {
  [Pipeline] sh
  03:57:23  + docker pull auto-gitlab.lgsvl.net:4567/
  03:57:23  invalid reference format
  03:57:23  + echo ABORT: cannot pull auto-gitlab.lgsvl.net:4567/
  03:57:23  ABORT: cannot pull auto-gitlab.lgsvl.net:4567/
  03:57:23  + exit 1

* because newly added parameter isn't added in jenkins job until the updated pipeline
  is executed at least once and unfortunately, when it's not picked there yet,
  it won't even use the default value specified in the pipeline and will just
  run with empty value which might cause unexpected build failures like this

* use ${env.OUTPUT_SUFFIX} instead of ${OUTPUT_SUFFIX}, because when "error"
  triggers "post" early it fails with:
  groovy.lang.MissingPropertyException: No such property: OUTPUT_SUFFIX for class: groovy.lang.Binding
  as in:
  https://auto-jenkins.lgsvl.net/view/Jenkins%20test/job/simulator-jansa-jenkins-wip-test/123/console

* testing params.SCENARIOS_RUNNER_DOCKER_TAG for null isn't enough,
  because it isn't null as long as the parameter definition appears
  in parameters section

* testing all params for empty doesn't help much as well, because some like
  BUILD_SIMULATOR_* in Bundle jobs could be intentinally set to empty

* unfortunatelly jenkins pipeline documentation still lacks:
  https://issues.jenkins.io/browse/INFRA-1053

diff --git a/Jenkins/Jenkinsfile b/Jenkins/Jenkinsfile
--- a/Jenkins/Jenkinsfile
+++ b/Jenkins/Jenkinsfile
@@ -49,9 +49,12 @@ pipeline {
 
   stages {
     stage("Build environment") {
-        steps {
-            sh label:"SIMULATOR env vars", script:"printenv | grep -E 'SIMULATOR|^SIM_' | sort"
+      steps {
+        script {
+          if (params.BUILD_LINUX && params.SCENARIOS_RUNNER_DOCKER_TAG == null || params.SCENARIOS_RUNNER_DOCKER_TAG == "") { error "Missing or empty parameter SCENARIOS_RUNNER_DOCKER_TAG! Value is required to bundle scenarios runner" }
         }
+        sh label:"SIMULATOR env vars", script:"printenv | grep -E 'SIMULATOR|^SIM_' | sort"
+      }
     }
 
     stage("Git") {
@@ -313,18 +316,19 @@ pipeline {
       steps {
         dir("Jenkins") {
           sh """
-            if ! docker pull ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG; then
-              echo "ABORT: cannot pull ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG"
+            echo "INFO: pulling docker image: ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG}"
+            if ! docker pull ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG}; then
+              echo "ABORT: cannot pull ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG}"
               exit 1
             fi
-            TEMP_CONT=`docker create ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG --name scenarios-runner-tmp`
+            TEMP_CONT=`docker create ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} --name scenarios-runner-tmp`
             if ! docker cp \$TEMP_CONT:/usr/share/scenarios-runner/scripts .; then
-              echo "ABORT: ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG doesn't have /usr/share/scenarios-runner/scripts directory"
+              echo "ABORT: ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} doesn't have /usr/share/scenarios-runner/scripts directory"
               docker rm \$TEMP_CONT
               exit 1
             fi
             if ! docker cp \$TEMP_CONT:/etc/wise-image-info.source .; then
-              echo "ABORT: ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG doesn't have /etc/wise-image-info.source file"
+              echo "ABORT: ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} doesn't have /etc/wise-image-info.source file"
               docker rm \$TEMP_CONT
               exit 1
             fi
@@ -335,7 +339,7 @@ pipeline {
             DST_TAG="lgsvl/simulator-scenarios-runner:simulator-build__${OUTPUT_SUFFIX}"
             DST_TARBALL=\$(echo \$DST_TAG | tr ':/' '-')
 
-            docker tag ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG \$DST_TAG
+            docker tag ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} \$DST_TAG
 
             echo "INFO: saving docker image \$DST_TAG to dist/docker/\$DST_TARBALL.tar"
             docker save \$DST_TAG > dist/docker/\$DST_TARBALL.tar
@@ -349,7 +353,7 @@ pipeline {
 
             unzip -o \$ZIP
             UNZIP=`basename \$ZIP | sed 's/-norunner\\.zip\$//g'`
-            echo "INFO: bundling simulator from \$UNZIP with scenarios runner from docker image \$SCENARIOS_RUNNER_DOCKER_TAG:"
+            echo "INFO: bundling simulator from \$UNZIP with scenarios runner from docker image ${SCENARIOS_RUNNER_DOCKER_TAG}:"
             cat wise-image-info.source
 
             dist/install-testcase-runtime.sh \$UNZIP copy
