Jenkinsfile-Release: Add bundleScenariosRunner step which creates another .zip with runner included
* it creates *-linux64-${GIT_TAG}.zip
  with the simulator from *-linux64-${GIT_TAG}-norunner.zip
  and the runner pulled from docker image specified in
  SCENARIOS_RUNNER_DOCKER_TAG (hdrp/scenarios/runner/jenkins:latest by default).

* fix cleaning temporary files in both Jenkinsfiles

[AUTO-4929] Modify the Jenkins job that builds Simulator to install the scenario runner files

diff --git a/Jenkins/Jenkinsfile-Release b/Jenkins/Jenkinsfile-Release
--- a/Jenkins/Jenkinsfile-Release
+++ b/Jenkins/Jenkinsfile-Release
@@ -17,6 +17,7 @@ pipeline {
 
   parameters {
     string(name: "CLOUD_URL", defaultValue: "${SIMULATOR_WISE_STAGING_URL}", description: "")
+    string(name: "SCENARIOS_RUNNER_DOCKER_TAG", defaultValue: "hdrp/scenarios/runner/jenkins:latest", description: "Repo and tag of scenarios runner docker image which will be bundled in zip archive")
     string(name: 'WISE_AWS_ECR_ACCOUNT_ID', defaultValue: '853285614468', description: 'The AWS account ID whose ECR will be used', trim: true)
     string(name: 'WISE_AWS_ECR_REGION', defaultValue: 'us-east-1', description: 'The AWS region where the ECR is located', trim: true)
     credentials( name: 'WISE_AWS_ECR_CREDENTIALS_ID', required: true, defaultValue: "simulator--aws-credentials", description: 'The credentials to be used for accessing the ECR', credentialType: 'com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl')
@@ -159,7 +160,6 @@ pipeline {
             ])
           }
 
-
           env.FORCE_REBUILD = "0"
           env.GIT_COMMIT = sh(returnStdout: true, script: "git rev-parse HEAD").trim()
           env.SIM_ENVIRONMENTS = sh(returnStdout: true, script: "./Jenkins/get-assets.sh Assets/External/Environments ${S3_DOWNLOAD_HOST} environment 1").trim()
@@ -263,15 +263,67 @@ pipeline {
         dir("Jenkins") {
           sh "UID=`id -u` docker-compose run --rm build-simulator linux"
         }
+        sh """
+          ZIP=`basename *-linux64-${GIT_TAG}.zip`
+          NORUNNER=`echo \$ZIP | sed 's/\\.zip\$/-norunner.zip/g'`
+          mv \$ZIP \$NORUNNER
+        """
       }
 
+      post {
+        success {
+          archiveArtifacts "*-linux64-${GIT_TAG}-norunner.zip"
+        }
+      }
+
+    } // Linux
+
+    stage("bundleScenariosRunner") {
+      steps {
+        dir("Jenkins") {
+          sh """
+            if ! docker pull ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG; then
+              echo "ABORT: cannot pull ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG"
+              exit 1
+            fi
+            TEMP_CONT=`docker create ${GITLAB_HOST}:4567/\$SCENARIOS_RUNNER_DOCKER_TAG --name scenarios-runner-tmp`
+            if ! docker cp \$TEMP_CONT:/usr/share/scenarios-runner/scripts .; then
+              echo "ABORT: ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} doesn't have /usr/share/scenarios-runner/scripts directory"
+              docker rm \$TEMP_CONT
+              exit 1
+            fi
+            if ! docker cp \$TEMP_CONT:/etc/wise-image-info.source .; then
+              echo "ABORT: ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} doesn't have /etc/wise-image-info.source file"
+              docker rm \$TEMP_CONT
+              exit 1
+            fi
+            docker rm \$TEMP_CONT
+
+            rm -rf dist
+            mkdir -p dist/docker
+            docker save ${GITLAB_HOST}:4567/${SCENARIOS_RUNNER_DOCKER_TAG} > dist/docker/lgsvl-simulator-scenarios-runner.tar
+            cp scripts/install-testcase-runtime.sh scripts/scenario_runner.sh dist
+
+            ZIP=../*-linux64-${GIT_TAG}-norunner.zip
+
+            unzip -o \$ZIP
+            UNZIP=`basename \$ZIP | sed 's/-norunner\\.zip\$//g'`
+            echo "INFO: bundling simulator from \$UNZIP with scenarios runner from docker image \$SCENARIOS_RUNNER_DOCKER_TAG:"
+            cat wise-image-info.source
+
+            dist/install-testcase-runtime.sh \$UNZIP copy
+            zip --symlinks -r ../\$UNZIP.zip \$UNZIP
+            rm -rvf dist \$UNZIP/
+            rm -f wise-image-info.source
+          """
+        }
+      }
       post {
         success {
           archiveArtifacts "*-linux64-${GIT_TAG}.zip"
         }
       }
-
-    } // Linux
+    }
 
     stage("uploadECR") {
       steps {
@@ -294,14 +346,14 @@ pipeline {
               fi
 
               cd ../Docker
-              cp -al ../*-linux64-${GIT_TAG}.zip .
+              cp -al ../*-linux64-${GIT_TAG}-norunner.zip .
               docker build --pull --no-cache \
-                  --build-arg "simulator_zipfile=*-linux64-${GIT_TAG}.zip" \
+                  --build-arg "simulator_zipfile=*-linux64-${GIT_TAG}-norunner.zip" \
                   --build-arg image_git_describe=\$(git describe --always --tags) \
                   --build-arg image_uuidgen=\$(uuidgen) \
                   -t \$DOCKER_REGISTRY/\$DOCKER_REPO:\$DOCKER_TAG .
               docker push \$DOCKER_REGISTRY/\$DOCKER_REPO:\$DOCKER_TAG
-              rm -fv *-linux64-${GIT_TAG}.zip
+              rm -fv *-linux64-${GIT_TAG}-norunner.zip
 
               docker image rm \
                 \$DOCKER_REGISTRY/\$DOCKER_REPO:\$DOCKER_TAG
